language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO_VERSION=2.0

install:
  - pip install pipenv
  - pipenv install
  - pipenv install django==$DJANGO_VERSION

script:
  - pipenv run python runtests.py
