language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
      # Only Django 2.0 is supported in Python 3.7
      env: DJANGO_VERSION=2.0

install:
  - pip install pipenv
  - pipenv install
  - pipenv install django==$DJANGO_VERSION

script:
  - pipenv run python runtests.py

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
