language: python

cache: pip

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1.2

matrix:
  include:
    # Python 3.7 still not available in usual distro
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO_VERSION=2.0
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO_VERSION=2.1.2
    # Django 2.1 not supported in Python 3.4
    - python: "3.4"
      env: DJANGO_VERSION=1.11
    - python: "3.4"
      env: DJANGO_VERSION=2.0

install:
  - pip install pipenv
  - pipenv install --skip-lock  # don't use nor update Pipfile.lock
  - pipenv install django==$DJANGO_VERSION

script:
  - pipenv run python runtests.py

before_deploy:
  # PyPI deploy fails if there are unstaged changes
  # Reset any unstaged changes (such as updates to Pipfile or Pipfile.lock)
  - git checkout -- .

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    # deploy only once
    python: "3.7"
    condition: "$DJANGO_VERSION = 2.1.2"
