language: python

# Cache dependencies between builds
cache: pip

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.6
      dist: xenial

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0

install:
  - pip install pipenv
  - pipenv install
  - pipenv install django==$DJANGO_VERSION

script:
  - echo "WIP"
