# Generated by Django 2.2.2 on 2019-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rest_framework_api_key", "0003_auto_20190609_1321")]

    # Blank operations to get custom verson of package on the same footing
    # as the latest version. We want to ensure that when we update to the
    # latest version, we already have the expected migrations applied and only
    # newer migrations will be added.
    operations = []
