# Generated by Django 2.2.2 on 2019-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rest_framework_api_key", "0003_auto_20190609_1321")]

    # This migration is named the same as the original package but its contents
    # are different. We need to ensure that when we can upgrade to the original
    # package things still work. We only want Django to apply newer migrations.
    operations = [
         migrations.AlterField(
             model_name='apikey',
             name='prefix',
             field=models.CharField(editable=False, max_length=8, unique=True),
         ),
    ]
